### ISSUE TITLE
print(f"ACC: {results['ACC']}")

### ISSUE THREAD

**Issue by timyerg** [Kari-Genomics-Lab/iDeLUCS#16]
Hello again and thank you for the tool.

New error was encountered while trying to print the line from the headline. 
Simply disabling it saved the day (`__main__.py,` line 200, put # at the beginning of the line), and the program was completed successfully.

However, I have another question:
Cluster 0 is the first cluster, or it means that sequences were not assigned to any cluster.

Please close the issue since it is already resolved for me.

**Comment by millanp95** [comment]
Thank you for catching the bug. 

Cluster 0 is the first cluster.
