### ISSUE TITLE
ERROR for class transition in utils.py

### ISSUE THREAD

**Issue by StackChan** [Kari-Genomics-Lab/iDeLUCS#19]
https://github.com/Kari-Genomics-Lab/iDeLUCS/blob/4c8df59a3d9e0fa2a1171a96afd5de7e1bbacc29/idelucs/utils.py#L75
`seq[i] = mutations[mutations.get(seq[i], N)]`
u use mutions twice，which means no mutations is used.
It is a apprent logical error. And the result is call for transition method would't work at all!!!

u can test the error with 
`        seq = bytearray(b'ACGTACGTACGTACGTACGTNNNN')

A, C, G, T, N = ord('A'), ord('C'), ord('G'), ord('T'), ord('N')
mutations = {A:G, G:A, T:C, C:T, N:N}

seq[1] = mutations[mutations.get(seq[1], N)]

print(seq)`

**Comment by millanp95** [comment]
Thank you, you are right
